### ISSUE TITLE
Determine UI framework

### ISSUE THREAD

**Issue by Apexal** [Apexal/wrathspriter#14]
Instead of styling everything ourselves to work well on all screen sizes, we should use a UI framework that covers all of the bases and gives us a cohesive design. We can customize our own themes to use our determined colors and styling. Here are some options:
- https://bulma.io/documentation/overview/
- https://getbootstrap.com/
- https://mui.com/
- https://materializecss.com/

Slightly different but more powerful is
- https://tailwindcss.com/

Has anyone had prior experience with any of these? Any opinions? Which do we think looks the best?

**Comment by talios0** [comment]
Taking a quick look at each of these, it seems like mui would be a good fit, but I don't see a strong reason to not consider any of the other ones. My suggestion of mui comes from the provided examples, which seems to be closer aligned with what we're trying to create.

In my own experience, I tend to lean toward building the CSS myself with SASS for each main screen layout (full-size desktop, half-size desktop, and mobile are the primary ones), but I can definitely see why we would want to use a UI framework instead.

**Comment by alexisvh** [comment]
Looking through these a bit from a subjective standpoint as someone with not much experience building websites or using frameworks, I think Mui and Bulma have the nicest looking examples, but I also don't see many cons with any of them.

I would personally love to work on customizing our themes/website layout so I would prefer an option with more customizability so that we can have a unique looking website that doesn't come straight from a template.

**Comment by Apexal** [comment]
Bulna holds a special place in my heart for its simplicity and customizability. MUI is very good looking but definitely heavier and more bloated, though it offers more cool components premade over Bulma. Tailwind is a very modern way of writing CSS but requires a lot more upfront effort and time so it might not be the best choice.

**Comment by Apexal** [comment]
In the spirit of moving quickly, let's go ahead with Bulma! I'll open a PR with it. If we need to, we can backtrack and switch to another in the future.
