### ISSUE TITLE
Determine export format of character

### ISSUE THREAD

**Issue by Apexal** [Apexal/wrathspriter#15]
Once a user finishes up their character in Wrathspriter, it needs to be exported in a way that stores a bunch of different types of data including
- strings (names, etc.)
- images (animation frames)
- audio (sound effects)

Let's discuss possible methods for this and their pros and cons.

**Comment by talios0** [comment]
Would it also be important to specify the data types used? (I would assume that having Wrathskeller assume a .mp3 when we give it a .wav would cause issues)

**Comment by Apexal** [comment]
We can use base64 encoding to turn all non text files like images and audio into text, and then store everything inside a JSON file in a format something like this:
```json
{
  "name": "Frank",
  "major": "CS",
  "minor": "ITWS",
  "moves": [
    {
      "type": "heavy",
      "frames": ["(crazy long base64 encoded string here) ..."]
    }
  ]
}
```

This would enable us to have just one file in a consistent format to transfer from Wrathspriter to Wrathskeller.

**Comment by Apexal** [comment]
> Would it also be important to specify the data types used? (I would assume that having Wrathskeller assume a .mp3 when we give it a .wav would cause issues)

Good question. Someone should take this on as a little research issue! In fact... I'll open an issue on this.

**Comment by talios0** [comment]
A new thought. Since we'll need to save this information so that users can see their characters later, this information should also be stored on the local system (probably through local storage cache).

**Comment by talios0** [comment]
The size of any method we use will be limited. For the cache, that amount is typically 10MB (sometimes 5MB) per origin. (See more [here](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria)).

Because we're storing images, we'll likely need more than that. The other options would be storing the data on the server (which we don't really want to do because then we have to authenticate users and keep data safe) and using IndexedDB, which creates a database on the client browser. This data is not necessarily persistent (though we can request it), remaining only until it is cleared (like when clearing cookies). We can request to use up to the space remaining on the hard drive. (More info [here](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API))

There are a few different ways to interact with IndexedDB in ReactJS. Here are two of them.
 - [React Indexed DB](https://www.npmjs.com/package/react-indexed-db)
 - [Dexie.js](https://dexie.org/docs/Tutorial/React)
